# 如果我们没有在properties文件中配置redis的ip，我们就需要在这里配置，反之这里不需要配置
#spring:
#  application:
#    name: SSO
#  cache:
#    type: redis
#  redis:
#    database: 0
#    host: 192.168.0.105
#    port: 6379
#    # 有密码填密码，没有密码不填
#    password:
#    # 连接超时时间（ms)
#    timeout: 1000ms
#    # 高版本springboot中使用jedis或者lettuce
#    jedis:
#      pool:
#        # 连接池最大连接数（负值表示无限制）
#        max-active: 8
#        # 连接池最大阻塞等待时间（负值无限制)
#        max-wait: 5000ms
#        # 最大空闲链接数
#        max-idle: 8
#        # 最小空闲链接数